# -*- coding: utf-8 -*-
"""proto 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vfs8q4Z0Lg7PkEwcesk1lyEaYkiG18TK
"""

from google.colab import drive

drive.mount('/content/drive')

from google.colab import drive

drive.mount('/content/drive')

import os

dataset_path = "/content/drive/MyDrive/CSIB-DDSM"

print(os.listdir(dataset_path))

csv_path = "/content/drive/MyDrive/CSIB-DDSM/csv"

print(os.listdir(csv_path))

import os

dataset_path = "/content/drive/MyDrive/CSIB-DDSM"
csv_path = os.path.join(dataset_path, "csv")

print("Dataset contents:")
print(os.listdir(dataset_path))

print("\nCSV contents:")
print(os.listdir(csv_path))

import pandas as pd

train_path = os.path.join(
    csv_path,
    "mass_case_description_train_set.csv"
)

df = pd.read_csv(train_path)

print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
display(df.head())

# Check the diagnosis labels

print("Pathology counts:")
print(df["pathology"].value_counts())

print("\nPathology percentages:")
print(df["pathology"].value_counts(normalize=True) * 100)

# Check for missing values

print("Missing values in each column:")
print(df.isnull().sum())

# Check whether the same patient appears multiple times

print("Total records:", len(df))
print("Unique patients:", df["patient_id"].nunique())

print("\nRecords per patient:")
print(df["patient_id"].value_counts().head(10))

for i, column in enumerate(df.columns):
    print(i, "->", column)

print("\nExample values from each column:\n")

for column in df.columns:
    print("=" * 60)
    print(column)
    print(df[column].head(3).to_string(index=False))

print("PATHOLOGY:")
print(df["pathology"].value_counts())

print("\nIMAGE FILE PATH:")
print(df["image file path"].head(10).to_string(index=False))

print("\nCROPPED IMAGE FILE PATH:")
print(df["cropped image file path"].head(10).to_string(index=False))

print("\nROI MASK FILE PATH:")
print(df["ROI mask file path"].head(10).to_string(index=False))

print("\nUnique pathology values:")
print(df["pathology"].unique())

# Look at the actual paths stored in the CSV

print("IMAGE FILE PATHS:")
display(df["image file path"].head(10))

print("\nCROPPED IMAGE FILE PATHS:")
display(df["cropped image file path"].head(10))

print("\nROI MASK FILE PATHS:")
display(df["ROI mask file path"].head(10))

print("\nPATHOLOGY:")
print(df["pathology"].value_counts())

import os

jpeg_path = "/content/drive/MyDrive/CSIB-DDSM/jpeg"

print("JPEG folder exists:", os.path.exists(jpeg_path))

if os.path.exists(jpeg_path):
    print("Contents:")
    print(os.listdir(jpeg_path)[:20])

import os

# Show first 20 files/folders recursively
count = 0

for root, dirs, files in os.walk(jpeg_path):
    for file in files:
        print(os.path.join(root, file))
        count += 1

        if count >= 20:
            break

    if count >= 20:
        break

import os

def check_path(path):
    """
    Check whether a path from the CSV exists
    relative to our dataset folder.
    """
    if pd.isna(path):
        return False

    path = str(path).replace("\\", "/")

    # Try directly
    if os.path.exists(path):
        return True

    # Try relative to dataset
    path_without_root = path.lstrip("/")
    candidate = os.path.join(
        "/content/drive/MyDrive/CSIB-DDSM",
        path_without_root
    )

    return os.path.exists(candidate)


# Test first 20 image paths
for path in df["image file path"].head(20):
    print(path, "->", check_path(path))

import os

extensions = {}

for root, dirs, files in os.walk(jpeg_path):
    for file in files:
        ext = os.path.splitext(file)[1].lower()

        if ext:
            extensions[ext] = extensions.get(ext, 0) + 1

print("File extensions found:")
print(extensions)

import os

extensions = {}

for root, dirs, files in os.walk(jpeg_path):
    for file in files:
        ext = os.path.splitext(file)[1].lower()

        if ext:
            extensions[ext] = extensions.get(ext, 0) + 1

print("File extensions found:")
print(extensions)

import kagglehub

path = kagglehub.dataset_download(
    "awsaf49/cbis-ddsm-breast-cancer-image-dataset"
)

print("Dataset downloaded to:")
print(path)

import kagglehub
import os
import pandas as pd
import numpy as np

print("Libraries imported successfully!")

path = kagglehub.dataset_download(
    "awsaf49/cbis-ddsm-breast-cancer-image-dataset"
)

print("Dataset path:")
print(path)

print("Dataset contents:")

for item in os.listdir(path):
    print(item)

import os

csv_folder = os.path.join(path, "csv")

print("CSV folder:")
print(csv_folder)

print("\nCSV files:")
print(os.listdir(csv_folder))

mass_train_path = os.path.join(
    csv_folder,
    "mass_case_description_train_set.csv"
)

mass_test_path = os.path.join(
    csv_folder,
    "mass_case_description_test_set.csv"
)

mass_train = pd.read_csv(mass_train_path)
mass_test = pd.read_csv(mass_test_path)

print("Training shape:", mass_train.shape)
print("Test shape:", mass_test.shape)

print("\nColumns:")
print(mass_train.columns.tolist())

print("Pathology distribution:")
print(mass_train["pathology"].value_counts())

print("\nFirst 5 rows:")
display(mass_train.head())

print("Missing values:")
print(mass_train.isnull().sum())

print(mass_train.shape)
print(mass_train.columns.tolist())
print(mass_train["pathology"].value_counts())

# Create binary labels
# MALIGNANT = 1
# BENIGN + BENIGN_WITHOUT_CALLBACK = 0

mass_train["label"] = mass_train["pathology"].map({
    "MALIGNANT": 1,
    "BENIGN": 0,
    "BENIGN_WITHOUT_CALLBACK": 0
})

print("Label distribution:")
print(mass_train["label"].value_counts())

print("\nMissing labels:")
print(mass_train["label"].isnull().sum())

# Look at the image path format

print(mass_train["image file path"].iloc[0])

jpeg_folder = os.path.join(path, "jpeg")

print("JPEG folder:")
print(jpeg_folder)

print("\nNumber of folders/files:")
print(len(os.listdir(jpeg_folder)))

from pathlib import Path

jpeg_files = list(Path(jpeg_folder).rglob("*.jpg"))

print("Total JPEG images found:", len(jpeg_files))

print("\nFirst 5 images:")

for img in jpeg_files[:5]:
    print(img)

# Create a lookup dictionary:
# UID → JPEG image path

jpeg_lookup = {}

for img_path in jpeg_files:
    parts = img_path.parts

    for part in parts:
        if part.startswith("1.3.6.1.4.1.9590.100.1.2."):
            jpeg_lookup[part] = str(img_path)
            break

print("UIDs found in JPEG dataset:", len(jpeg_lookup))

# Show a few examples
for uid, img_path in list(jpeg_lookup.items())[:5]:
    print("\nUID:", uid)
    print("Image:", img_path)

import re

def extract_uids(csv_path):

    matches = re.findall(
        r"1\.3\.6\.1\.4\.1\.9590\.100\.1\.2\.\d+",
        str(csv_path)
    )

    return matches

example = mass_train["image file path"].iloc[0]

print("CSV path:")
print(example)

print("\nExtracted UIDs:")
print(extract_uids(example))

def find_matching_jpeg(csv_path):

    uids = extract_uids(csv_path)

    for uid in uids:
        if uid in jpeg_lookup:
            return jpeg_lookup[uid]

    return None

test_path = mass_train["image file path"].iloc[0]

matched_image = find_matching_jpeg(test_path)

print("CSV path:")
print(test_path)

print("\nMatched JPEG:")
print(matched_image)

mass_train["image_path"] = mass_train[
    "image file path"
].apply(find_matching_jpeg)

print("Total records:", len(mass_train))

print("Matched images:",
      mass_train["image_path"].notna().sum())

print("Unmatched images:",
      mass_train["image_path"].isna().sum())

# Keep only successfully matched images
clean_df = mass_train.dropna(
    subset=["image_path"]
).copy()

# Keep only the columns we need
clean_df = clean_df[
    ["patient_id", "image_path", "pathology", "label"]
].copy()

print("Total usable images:", len(clean_df))

print("\nLabels:")
print(clean_df["label"].value_counts())

print("\nPatients:")
print(clean_df["patient_id"].nunique())

from sklearn.model_selection import train_test_split

# Unique patients
patients = clean_df["patient_id"].unique()

# 70% train, 30% temporary
train_patients, temp_patients = train_test_split(
    patients,
    test_size=0.30,
    random_state=42
)

# Split remaining 30% into 15% validation + 15% test
val_patients, test_patients = train_test_split(
    temp_patients,
    test_size=0.50,
    random_state=42
)

train_df = clean_df[
    clean_df["patient_id"].isin(train_patients)
].copy()

val_df = clean_df[
    clean_df["patient_id"].isin(val_patients)
].copy()

test_df = clean_df[
    clean_df["patient_id"].isin(test_patients)
].copy()

print("TRAIN:", len(train_df))
print("VALIDATION:", len(val_df))
print("TEST:", len(test_df))

print("TRAIN")
print(train_df["label"].value_counts())

print("\nVALIDATION")
print(val_df["label"].value_counts())

print("\nTEST")
print(test_df["label"].value_counts())

import tensorflow as tf
import numpy as np
from PIL import Image

IMG_SIZE = (224, 224)
BATCH_SIZE = 16


def create_dataset(dataframe, shuffle=True):

    def generator():

        for _, row in dataframe.iterrows():

            # Load image
            image = Image.open(
                row["image_path"]
            ).convert("RGB")

            # Resize
            image = image.resize(IMG_SIZE)

            # Convert to numpy
            image = np.array(image).astype("float32") / 255.0

            # Label
            label = np.float32(row["label"])

            yield image, label

    dataset = tf.data.Dataset.from_generator(
        generator,
        output_signature=(
            tf.TensorSpec(
                shape=(224, 224, 3),
                dtype=tf.float32
            ),
            tf.TensorSpec(
                shape=(),
                dtype=tf.float32
            )
        )
    )

    if shuffle:
        dataset = dataset.shuffle(
            buffer_size=min(len(dataframe), 1000),
            reshuffle_each_iteration=True
        )

    dataset = dataset.batch(BATCH_SIZE)
    dataset = dataset.prefetch(
        tf.data.AUTOTUNE
    )

    return dataset

import tensorflow as tf
import numpy as np
from PIL import Image

IMG_SIZE = (224, 224)
BATCH_SIZE = 16

def create_dataset(dataframe, shuffle=True):

    def generator():

        for _, row in dataframe.iterrows():

            image = Image.open(
                row["image_path"]
            ).convert("RGB")

            image = image.resize(IMG_SIZE)

            image = np.array(image).astype(
                "float32"
            ) / 255.0

            label = np.float32(row["label"])

            yield image, label

    dataset = tf.data.Dataset.from_generator(
        generator,
        output_signature=(
            tf.TensorSpec(
                shape=(224, 224, 3),
                dtype=tf.float32
            ),
            tf.TensorSpec(
                shape=(),
                dtype=tf.float32
            )
        )
    )

    if shuffle:
        dataset = dataset.shuffle(
            buffer_size=min(len(dataframe), 1000),
            reshuffle_each_iteration=True
        )

    dataset = dataset.batch(BATCH_SIZE)
    dataset = dataset.prefetch(tf.data.AUTOTUNE)

    return dataset

print("create_dataset function is ready!")

# ============================================================
# RECOVER ALL DATA VARIABLES AFTER COLAB RUNTIME RESET
# ============================================================

import os
import re
import pandas as pd
import numpy as np
from pathlib import Path
from sklearn.model_selection import train_test_split
import tensorflow as tf
from PIL import Image

print("Starting recovery...")

# ------------------------------------------------------------
# 1. CSV PATH
# ------------------------------------------------------------

csv_folder = os.path.join(path, "csv")

mass_train_path = os.path.join(
    csv_folder,
    "mass_case_description_train_set.csv"
)

mass_train = pd.read_csv(mass_train_path)

print("CSV loaded:", mass_train.shape)


# ------------------------------------------------------------
# 2. CREATE LABELS
# ------------------------------------------------------------

mass_train["label"] = mass_train["pathology"].map({
    "MALIGNANT": 1,
    "BENIGN": 0,
    "BENIGN_WITHOUT_CALLBACK": 0
})

mass_train = mass_train.dropna(
    subset=["label"]
).copy()

mass_train["label"] = mass_train["label"].astype(int)

print("\nLabels:")
print(mass_train["label"].value_counts())


# ------------------------------------------------------------
# 3. FIND JPEG IMAGES
# ------------------------------------------------------------

jpeg_folder = os.path.join(path, "jpeg")

jpeg_files = list(
    Path(jpeg_folder).rglob("*.jpg")
)

print("\nJPEG images found:", len(jpeg_files))


# ------------------------------------------------------------
# 4. CREATE JPEG UID LOOKUP
# ------------------------------------------------------------

jpeg_lookup = {}

for img_path in jpeg_files:

    for part in img_path.parts:

        if part.startswith(
            "1.3.6.1.4.1.9590.100.1.2."
        ):

            jpeg_lookup[part] = str(img_path)
            break

print(
    "JPEG UIDs found:",
    len(jpeg_lookup)
)


# ------------------------------------------------------------
# 5. EXTRACT UIDs FROM CSV PATH
# ------------------------------------------------------------

def extract_uids(csv_path):

    return re.findall(
        r"1\.3\.6\.1\.4\.1\.9590\.100\.1\.2\.\d+",
        str(csv_path)
    )


# ------------------------------------------------------------
# 6. MATCH CSV → JPEG
# ------------------------------------------------------------

def find_matching_jpeg(csv_path):

    uids = extract_uids(csv_path)

    for uid in uids:

        if uid in jpeg_lookup:

            return jpeg_lookup[uid]

    return None


mass_train["image_path"] = mass_train[
    "image file path"
].apply(find_matching_jpeg)


print("\nMatching results:")
print(
    "Total:",
    len(mass_train)
)

print(
    "Matched:",
    mass_train["image_path"].notna().sum()
)

print(
    "Unmatched:",
    mass_train["image_path"].isna().sum()
)


# ------------------------------------------------------------
# 7. CLEAN DATASET
# ------------------------------------------------------------

clean_df = mass_train.dropna(
    subset=["image_path"]
).copy()

clean_df = clean_df[
    [
        "patient_id",
        "image_path",
        "pathology",
        "label"
    ]
].copy()

print(
    "\nUsable images:",
    len(clean_df)
)

print(
    "\nUsable labels:"
)

print(
    clean_df["label"].value_counts()
)


# ------------------------------------------------------------
# 8. PATIENT-LEVEL SPLIT
# ------------------------------------------------------------

patients = clean_df[
    "patient_id"
].unique()

train_patients, temp_patients = train_test_split(
    patients,
    test_size=0.30,
    random_state=42
)

val_patients, test_patients = train_test_split(
    temp_patients,
    test_size=0.50,
    random_state=42
)


train_df = clean_df[
    clean_df["patient_id"].isin(train_patients)
].copy()

val_df = clean_df[
    clean_df["patient_id"].isin(val_patients)
].copy()

test_df = clean_df[
    clean_df["patient_id"].isin(test_patients)
].copy()


print("\nPATIENT-LEVEL SPLIT")
print(
    "Train:",
    len(train_df)
)

print(
    "Validation:",
    len(val_df)
)

print(
    "Test:",
    len(test_df)
)


# ------------------------------------------------------------
# 9. DATASET GENERATOR
# ------------------------------------------------------------

IMG_SIZE = (224, 224)
BATCH_SIZE = 16


def create_dataset(dataframe, shuffle=True):

    def generator():

        for _, row in dataframe.iterrows():

            image = Image.open(
                row["image_path"]
            ).convert("RGB")

            image = image.resize(
                IMG_SIZE
            )

            image = np.array(
                image
            ).astype("float32") / 255.0

            label = np.float32(
                row["label"]
            )

            yield image, label


    dataset = tf.data.Dataset.from_generator(

        generator,

        output_signature=(

            tf.TensorSpec(
                shape=(224, 224, 3),
                dtype=tf.float32
            ),

            tf.TensorSpec(
                shape=(),
                dtype=tf.float32
            )
        )
    )


    if shuffle:

        dataset = dataset.shuffle(
            buffer_size=min(
                len(dataframe),
                1000
            )
        )


    dataset = dataset.batch(
        BATCH_SIZE
    )

    dataset = dataset.prefetch(
        tf.data.AUTOTUNE
    )

    return dataset


# ------------------------------------------------------------
# 10. CREATE DATASETS
# ------------------------------------------------------------

train_ds = create_dataset(
    train_df,
    shuffle=True
)

val_ds = create_dataset(
    val_df,
    shuffle=False
)

test_ds = create_dataset(
    test_df,
    shuffle=False
)


# ------------------------------------------------------------
# 11. TEST ONE BATCH
# ------------------------------------------------------------

images, labels = next(
    iter(train_ds)
)


print("\nSUCCESS!")
print(
    "Image batch:",
    images.shape
)

print(
    "Label batch:",
    labels.shape
)

print(
    "Example labels:",
    labels.numpy()[:10]
)

import kagglehub

path = kagglehub.dataset_download(
    "awsaf49/cbis-ddsm-breast-cancer-image-dataset"
)

print("Dataset path:")
print(path)

import os

print(os.listdir(path))

print(path)
print(os.listdir(path))

path = "/kaggle/input/cbis-ddsm-breast-cancer-image-dataset"

print(path)
print(os.listdir(path))

import os
import re
import pandas as pd
import numpy as np
from pathlib import Path
from sklearn.model_selection import train_test_split
import tensorflow as tf
from PIL import Image

# CSV
csv_folder = os.path.join(path, "csv")

mass_train_path = os.path.join(
    csv_folder,
    "mass_case_description_train_set.csv"
)

mass_train = pd.read_csv(mass_train_path)

print("CSV shape:", mass_train.shape)

# Labels
mass_train["label"] = mass_train["pathology"].map({
    "MALIGNANT": 1,
    "BENIGN": 0,
    "BENIGN_WITHOUT_CALLBACK": 0
})

mass_train = mass_train.dropna(subset=["label"]).copy()
mass_train["label"] = mass_train["label"].astype(int)

print("\nLabels:")
print(mass_train["label"].value_counts())

# JPEG files
jpeg_folder = os.path.join(path, "jpeg")

jpeg_files = list(Path(jpeg_folder).rglob("*.jpg"))

print("\nJPEG files:", len(jpeg_files))

# UID lookup
jpeg_lookup = {}

for img_path in jpeg_files:
    for part in img_path.parts:
        if part.startswith("1.3.6.1.4.1.9590.100.1.2."):
            jpeg_lookup[part] = str(img_path)
            break

print("JPEG UIDs:", len(jpeg_lookup))

# Extract UIDs
def extract_uids(csv_path):
    return re.findall(
        r"1\.3\.6\.1\.4\.1\.9590\.100\.1\.2\.\d+",
        str(csv_path)
    )

# Match
def find_matching_jpeg(csv_path):
    for uid in extract_uids(csv_path):
        if uid in jpeg_lookup:
            return jpeg_lookup[uid]
    return None

mass_train["image_path"] = mass_train[
    "image file path"
].apply(find_matching_jpeg)

print("\nMatching:")
print("Total:", len(mass_train))
print("Matched:", mass_train["image_path"].notna().sum())
print("Unmatched:", mass_train["image_path"].isna().sum())

# Clean
clean_df = mass_train.dropna(
    subset=["image_path"]
).copy()

clean_df = clean_df[
    ["patient_id", "image_path", "pathology", "label"]
].copy()

print("\nUsable images:", len(clean_df))

# Patient-level split
patients = clean_df["patient_id"].unique()

train_patients, temp_patients = train_test_split(
    patients,
    test_size=0.30,
    random_state=42
)

val_patients, test_patients = train_test_split(
    temp_patients,
    test_size=0.50,
    random_state=42
)

train_df = clean_df[
    clean_df["patient_id"].isin(train_patients)
].copy()

val_df = clean_df[
    clean_df["patient_id"].isin(val_patients)
].copy()

test_df = clean_df[
    clean_df["patient_id"].isin(test_patients)
].copy()

print("\nPatient-level split:")
print("Train:", len(train_df))
print("Validation:", len(val_df))
print("Test:", len(test_df))

import tensorflow as tf
import numpy as np
from PIL import Image

IMG_SIZE = (224, 224)
BATCH_SIZE = 16

def create_dataset(dataframe, shuffle=True):

    def generator():

        for _, row in dataframe.iterrows():

            image = Image.open(
                row["image_path"]
            ).convert("RGB")

            image = image.resize(IMG_SIZE)

            image = np.array(
                image
            ).astype("float32") / 255.0

            label = np.float32(
                row["label"]
            )

            yield image, label

    dataset = tf.data.Dataset.from_generator(
        generator,
        output_signature=(
            tf.TensorSpec(
                shape=(224, 224, 3),
                dtype=tf.float32
            ),
            tf.TensorSpec(
                shape=(),
                dtype=tf.float32
            )
        )
    )

    if shuffle:
        dataset = dataset.shuffle(
            min(len(dataframe), 1000),
            reshuffle_each_iteration=True
        )

    dataset = dataset.batch(BATCH_SIZE)
    dataset = dataset.prefetch(
        tf.data.AUTOTUNE
    )

    return dataset


train_ds = create_dataset(train_df, True)
val_ds = create_dataset(val_df, False)
test_ds = create_dataset(test_df, False)

print("Datasets ready!")

from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras import layers, Model

# Pretrained EfficientNetB0
base_model = EfficientNetB0(
    include_top=False,
    weights="imagenet",
    input_shape=(224, 224, 3)
)

# Freeze initially
base_model.trainable = False

# Build classifier
inputs = layers.Input(
    shape=(224, 224, 3)
)

x = base_model(
    inputs,
    training=False
)

x = layers.GlobalAveragePooling2D()(x)

x = layers.Dropout(0.3)(x)

outputs = layers.Dense(
    1,
    activation="sigmoid"
)(x)

model = Model(
    inputs,
    outputs
)

model.summary()

model.compile(

    optimizer=tf.keras.optimizers.Adam(
        learning_rate=1e-3
    ),

    loss="binary_crossentropy",

    metrics=[
        "accuracy",

        tf.keras.metrics.AUC(
            name="auc"
        ),

        tf.keras.metrics.Precision(
            name="precision"
        ),

        tf.keras.metrics.Recall(
            name="recall"
        )
    ]
)

print("Model compiled!")

import tensorflow as tf

print("TensorFlow version:", tf.__version__)

print("Model exists:", "model" in globals())
print("Train dataset exists:", "train_ds" in globals())
print("Validation dataset exists:", "val_ds" in globals())

print("path:", "path" in globals())
print("train_df:", "train_df" in globals())
print("val_df:", "val_df" in globals())
print("test_df:", "test_df" in globals())

# ============================================================
# COMPLETE RECOVERY AFTER COLAB/KAGGLE RUNTIME RESET
# ============================================================

import os
import re
import pandas as pd
import numpy as np
from pathlib import Path
from sklearn.model_selection import train_test_split
import tensorflow as tf
from PIL import Image

# ------------------------------------------------------------
# 1. DATASET PATH
# ------------------------------------------------------------

path = "/kaggle/input/cbis-ddsm-breast-cancer-image-dataset"

print("Dataset:", path)
print("Contents:", os.listdir(path))


# ------------------------------------------------------------
# 2. LOAD CSV
# ------------------------------------------------------------

csv_folder = os.path.join(path, "csv")

mass_train_path = os.path.join(
    csv_folder,
    "mass_case_description_train_set.csv"
)

mass_train = pd.read_csv(mass_train_path)

print("\nCSV shape:", mass_train.shape)


# ------------------------------------------------------------
# 3. CREATE LABELS
# ------------------------------------------------------------

mass_train["label"] = mass_train["pathology"].map({
    "MALIGNANT": 1,
    "BENIGN": 0,
    "BENIGN_WITHOUT_CALLBACK": 0
})

mass_train = mass_train.dropna(
    subset=["label"]
).copy()

mass_train["label"] = mass_train["label"].astype(int)

print("\nLabels:")
print(mass_train["label"].value_counts())


# ------------------------------------------------------------
# 4. FIND JPEG FILES
# ------------------------------------------------------------

jpeg_folder = os.path.join(path, "jpeg")

jpeg_files = list(
    Path(jpeg_folder).rglob("*.jpg")
)

print("\nJPEG files:", len(jpeg_files))


# ------------------------------------------------------------
# 5. BUILD UID → JPEG LOOKUP
# ------------------------------------------------------------

jpeg_lookup = {}

for img_path in jpeg_files:

    for part in img_path.parts:

        if part.startswith(
            "1.3.6.1.4.1.9590.100.1.2."
        ):

            jpeg_lookup[part] = str(img_path)
            break

print("JPEG UIDs:", len(jpeg_lookup))


# ------------------------------------------------------------
# 6. MATCH CSV → JPEG
# ------------------------------------------------------------

def extract_uids(csv_path):

    return re.findall(
        r"1\.3\.6\.1\.4\.1\.9590\.100\.1\.2\.\d+",
        str(csv_path)
    )


def find_matching_jpeg(csv_path):

    for uid in extract_uids(csv_path):

        if uid in jpeg_lookup:

            return jpeg_lookup[uid]

    return None


mass_train["image_path"] = mass_train[
    "image file path"
].apply(find_matching_jpeg)


print("\nMATCHING")
print("Total:", len(mass_train))
print(
    "Matched:",
    mass_train["image_path"].notna().sum()
)
print(
    "Unmatched:",
    mass_train["image_path"].isna().sum()
)


# ------------------------------------------------------------
# 7. CLEAN DATA
# ------------------------------------------------------------

clean_df = mass_train.dropna(
    subset=["image_path"]
).copy()

clean_df = clean_df[
    [
        "patient_id",
        "image_path",
        "pathology",
        "label"
    ]
].copy()

print(
    "\nUsable images:",
    len(clean_df)
)


# ------------------------------------------------------------
# 8. PATIENT-LEVEL SPLIT
# ------------------------------------------------------------

patients = clean_df[
    "patient_id"
].unique()

train_patients, temp_patients = train_test_split(
    patients,
    test_size=0.30,
    random_state=42
)

val_patients, test_patients = train_test_split(
    temp_patients,
    test_size=0.50,
    random_state=42
)

train_df = clean_df[
    clean_df["patient_id"].isin(train_patients)
].copy()

val_df = clean_df[
    clean_df["patient_id"].isin(val_patients)
].copy()

test_df = clean_df[
    clean_df["patient_id"].isin(test_patients)
].copy()

print("\nPATIENT SPLIT")
print("Train:", len(train_df))
print("Validation:", len(val_df))
print("Test:", len(test_df))


# ------------------------------------------------------------
# 9. CREATE TENSORFLOW DATASETS
# ------------------------------------------------------------

IMG_SIZE = (224, 224)
BATCH_SIZE = 16


def create_dataset(dataframe, shuffle=False):

    def generator():

        for _, row in dataframe.iterrows():

            image = Image.open(
                row["image_path"]
            ).convert("RGB")

            image = image.resize(
                IMG_SIZE
            )

            image = np.array(
                image
            ).astype("float32") / 255.0

            label = np.float32(
                row["label"]
            )

            yield image, label


    dataset = tf.data.Dataset.from_generator(

        generator,

        output_signature=(

            tf.TensorSpec(
                shape=(224, 224, 3),
                dtype=tf.float32
            ),

            tf.TensorSpec(
                shape=(),
                dtype=tf.float32
            )
        )
    )


    if shuffle:

        dataset = dataset.shuffle(
            min(len(dataframe), 1000)
        )


    return dataset.batch(
        BATCH_SIZE
    ).prefetch(
        tf.data.AUTOTUNE
    )


train_ds = create_dataset(
    train_df,
    shuffle=True
)

val_ds = create_dataset(
    val_df,
    shuffle=False
)

test_ds = create_dataset(
    test_df,
    shuffle=False
)


# ------------------------------------------------------------
# 10. FINAL CHECK
# ------------------------------------------------------------

images, labels = next(
    iter(train_ds)
)

print("\n================================")
print("✅ RECOVERY COMPLETE")
print("================================")

print(
    "Image batch:",
    images.shape
)

print(
    "Label batch:",
    labels.shape
)

print(
    "Example labels:",
    labels.numpy()[:10]
)

import tensorflow as tf
from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras import layers, Model

print("TensorFlow:", tf.__version__)

base_model = EfficientNetB0(
    include_top=False,
    weights="imagenet",
    input_shape=(224, 224, 3)
)

base_model.trainable = False

inputs = layers.Input(shape=(224, 224, 3))

x = base_model(inputs, training=False)
x = layers.GlobalAveragePooling2D()(x)
x = layers.Dropout(0.3)(x)

outputs = layers.Dense(
    1,
    activation="sigmoid"
)(x)

model = Model(inputs, outputs)

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss="binary_crossentropy",
    metrics=[
        "accuracy",
        tf.keras.metrics.AUC(name="auc"),
        tf.keras.metrics.Precision(name="precision"),
        tf.keras.metrics.Recall(name="recall")
    ]
)

print("✅ EfficientNetB0 ready")

early_stop = tf.keras.callbacks.EarlyStopping(
    monitor="val_auc",
    mode="max",
    patience=2,
    restore_best_weights=True
)

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=5,
    callbacks=[early_stop]
)

import tensorflow as tf
import numpy as np
from PIL import Image

IMG_SIZE = (224, 224)
BATCH_SIZE = 16

def create_dataset(df, shuffle=False):

    paths = df["image_path"].values
    labels = df["label"].values.astype("float32")

    def load_image(path, label):
        image = tf.io.read_file(path)
        image = tf.image.decode_jpeg(
            image,
            channels=3
        )
        image = tf.image.resize(
            image,
            IMG_SIZE
        )
        image = tf.cast(
            image,
            tf.float32
        ) / 255.0

        return image, label

    dataset = tf.data.Dataset.from_tensor_slices(
        (paths, labels)
    )

    if shuffle:
        dataset = dataset.shuffle(
            len(df),
            seed=42
        )

    dataset = dataset.map(
        load_image,
        num_parallel_calls=tf.data.AUTOTUNE
    )

    dataset = dataset.batch(BATCH_SIZE)
    dataset = dataset.prefetch(
        tf.data.AUTOTUNE
    )

    return dataset


train_ds = create_dataset(train_df, True)
val_ds = create_dataset(val_df, False)
test_ds = create_dataset(test_df, False)

print("✅ train_ds:", tf.data.experimental.cardinality(train_ds).numpy())
print("✅ val_ds:", tf.data.experimental.cardinality(val_ds).numpy())
print("✅ test_ds:", tf.data.experimental.cardinality(test_ds).numpy())

# FAST RECOVERY — no kaggle download

import os
import re
import pandas as pd
import numpy as np
import tensorflow as tf
from pathlib import Path
from sklearn.model_selection import train_test_split

path = "/kaggle/input/cbis-ddsm-breast-cancer-image-dataset"

# ============================================================
# 1. LOAD CSV
# ============================================================

csv_path = os.path.join(
    path,
    "csv",
    "mass_case_description_train_set.csv"
)

mass_train = pd.read_csv(csv_path)

mass_train["label"] = mass_train["pathology"].map({
    "MALIGNANT": 1,
    "BENIGN": 0,
    "BENIGN_WITHOUT_CALLBACK": 0
})

mass_train = mass_train.dropna(
    subset=["label"]
).copy()

mass_train["label"] = mass_train["label"].astype(int)

print("CSV:", mass_train.shape)


# ============================================================
# 2. JPEG UID LOOKUP
# ============================================================

jpeg_folder = os.path.join(path, "jpeg")

jpeg_lookup = {}

for p in Path(jpeg_folder).rglob("*.jpg"):

    for part in p.parts:

        if part.startswith(
            "1.3.6.1.4.1.9590.100.1.2."
        ):
            jpeg_lookup[part] = str(p)
            break

print("JPEG UIDs:", len(jpeg_lookup))


# ============================================================
# 3. MATCH CSV → JPEG
# ============================================================

def get_image(csv_path):

    uids = re.findall(
        r"1\.3\.6\.1\.4\.1\.9590\.100\.1\.2\.\d+",
        str(csv_path)
    )

    for uid in uids:

        if uid in jpeg_lookup:
            return jpeg_lookup[uid]

    return None


mass_train["image_path"] = mass_train[
    "image file path"
].apply(get_image)

clean_df = mass_train.dropna(
    subset=["image_path"]
).copy()

clean_df = clean_df[
    ["patient_id", "image_path", "pathology", "label"]
]

print("Matched:", len(clean_df))


# ============================================================
# 4. PATIENT-LEVEL SPLIT
# ============================================================

patients = clean_df["patient_id"].unique()

train_patients, temp_patients = train_test_split(
    patients,
    test_size=0.30,
    random_state=42
)

val_patients, test_patients = train_test_split(
    temp_patients,
    test_size=0.50,
    random_state=42
)

train_df = clean_df[
    clean_df["patient_id"].isin(train_patients)
].copy()

val_df = clean_df[
    clean_df["patient_id"].isin(val_patients)
].copy()

test_df = clean_df[
    clean_df["patient_id"].isin(test_patients)
].copy()

print("Train:", len(train_df))
print("Validation:", len(val_df))
print("Test:", len(test_df))


# ============================================================
# 5. FAST TENSORFLOW DATASET
# ============================================================

IMG_SIZE = (224, 224)
BATCH_SIZE = 16

def create_dataset(df, shuffle=False):

    paths = df["image_path"].values
    labels = df["label"].values.astype("float32")

    ds = tf.data.Dataset.from_tensor_slices(
        (paths, labels)
    )

    def load_image(path, label):

        image = tf.io.read_file(path)

        image = tf.image.decode_jpeg(
            image,
            channels=3
        )

        image = tf.image.resize(
            image,
            IMG_SIZE
        )

        image = tf.cast(
            image,
            tf.float32
        ) / 255.0

        return image, label

    if shuffle:
        ds = ds.shuffle(
            len(df),
            seed=42
        )

    ds = ds.map(
        load_image,
        num_parallel_calls=tf.data.AUTOTUNE
    )

    return ds.batch(BATCH_SIZE).prefetch(
        tf.data.AUTOTUNE
    )


train_ds = create_dataset(
    train_df,
    True
)

val_ds = create_dataset(
    val_df,
    False
)

test_ds = create_dataset(
    test_df,
    False
)

print("\n================================")
print("✅ EVERYTHING READY")
print("================================")

print("Train batches:",
      tf.data.experimental.cardinality(train_ds).numpy())

print("Validation batches:",
      tf.data.experimental.cardinality(val_ds).numpy())

print("Test batches:",
      tf.data.experimental.cardinality(test_ds).numpy())

print("Model:", "model" in globals())
print("Train:", "train_ds" in globals())
print("Validation:", "val_ds" in globals())

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=5
)

import tensorflow as tf

early_stop = tf.keras.callbacks.EarlyStopping(
    monitor="val_auc",
    mode="max",
    patience=2,
    restore_best_weights=True
)

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=5,
    callbacks=[early_stop]
)

results = model.evaluate(
    test_ds,
    return_dict=True
)

print("\n===== TEST RESULTS =====")

for name, value in results.items():
    print(f"{name}: {value:.4f}")

base_model.trainable = True

# Freeze the first ~80% of EfficientNet
for layer in base_model.layers[:-30]:
    layer.trainable = False

model.compile(
    optimizer=tf.keras.optimizers.Adam(
        learning_rate=1e-5
    ),
    loss="binary_crossentropy",
    metrics=[
        "accuracy",
        tf.keras.metrics.AUC(name="auc"),
        tf.keras.metrics.Precision(name="precision"),
        tf.keras.metrics.Recall(name="recall")
    ]
)

fine_tune_history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=5,
    callbacks=[
        tf.keras.callbacks.EarlyStopping(
            monitor="val_auc",
            mode="max",
            patience=2,
            restore_best_weights=True
        )
    ]
)

results = model.evaluate(
    test_ds,
    return_dict=True
)

print("\n===== FINAL TEST RESULTS =====")

for name, value in results.items():
    print(f"{name}: {value:.4f}")

model.save("diagnyx_efficientnet_b0.keras")

print("✅ Model saved!")

# Show the last layers of EfficientNet
for i, layer in enumerate(base_model.layers[-30:]):
    print(i - 30, layer.name, type(layer).__name__)

import tensorflow as tf

gradcam_layer = base_model.get_layer("top_conv")

grad_model = tf.keras.models.Model(
    inputs=model.inputs,
    outputs=[
        gradcam_layer.output,
        model.output
    ]
)

print("Grad-CAM layer:", gradcam_layer.name)
print("✅ Grad-CAM model created")

import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from PIL import Image


def generate_gradcam(image_path):

    # -----------------------------
    # Load image
    # -----------------------------

    original = Image.open(
        image_path
    ).convert("RGB")

    original = original.resize(
        (224, 224)
    )

    image_array = np.array(
        original
    ).astype("float32") / 255.0

    x = np.expand_dims(
        image_array,
        axis=0
    )

    # -----------------------------
    # Gradient calculation
    # -----------------------------

    with tf.GradientTape() as tape:

        conv_outputs, predictions = grad_model(
            x,
            training=False
        )

        probability = predictions[:, 0]

    gradients = tape.gradient(
        probability,
        conv_outputs
    )

    # -----------------------------
    # Global average pooling
    # -----------------------------

    pooled_gradients = tf.reduce_mean(
        gradients,
        axis=(1, 2)
    )

    conv_outputs = conv_outputs[0]
    pooled_gradients = pooled_gradients[0]

    heatmap = tf.reduce_sum(
        conv_outputs * pooled_gradients,
        axis=-1
    )

    # -----------------------------
    # Normalize heatmap
    # -----------------------------

    heatmap = tf.maximum(
        heatmap,
        0
    )

    max_value = tf.reduce_max(
        heatmap
    )

    heatmap = heatmap / (
        max_value + 1e-8
    )

    heatmap = heatmap.numpy()

    # -----------------------------
    # Prediction
    # -----------------------------

    malignant_probability = float(
        probability.numpy()[0]
    )

    if malignant_probability >= 0.5:

        prediction = "MALIGNANT"

        confidence = malignant_probability

    else:

        prediction = "BENIGN"

        confidence = 1 - malignant_probability

    # -----------------------------
    # Display
    # -----------------------------

    plt.figure(figsize=(12, 5))

    # Original
    plt.subplot(1, 2, 1)

    plt.imshow(original)

    plt.title(
        f"Original\nPrediction: {prediction}"
    )

    plt.axis("off")

    # Heatmap
    plt.subplot(1, 2, 2)

    plt.imshow(original)

    plt.imshow(
        heatmap,
        cmap="jet",
        alpha=0.45
    )

    plt.title(
        f"Grad-CAM\n"
        f"Malignant probability: "
        f"{malignant_probability:.2%}"
    )

    plt.axis("off")

    plt.tight_layout()

    plt.show()

    return {
        "prediction": prediction,
        "confidence": confidence,
        "malignant_probability": malignant_probability,
        "heatmap": heatmap
    }

test_image = test_df.iloc[0]["image_path"]

print("Testing image:")
print(test_image)

result = generate_gradcam(test_image)

print("\n===== DIAGNYX AI RESULT =====")
print("Prediction:", result["prediction"])
print(
    "Confidence:",
    f"{result['confidence']:.2%}"
)
print(
    "Malignant Probability:",
    f"{result['malignant_probability']:.2%}"
)

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

# Get the actual EfficientNet layer inside your trained model
base_model = model.layers[1]

print("Base model:", base_model.name)

# Find the last convolutional layer
for layer in reversed(base_model.layers):
    if isinstance(layer, tf.keras.layers.Conv2D):
        gradcam_layer = layer
        break

print("Grad-CAM layer:", gradcam_layer.name)

def generate_gradcam(image_path):

    # -----------------------------
    # Load image
    # -----------------------------

    img = Image.open(
        image_path
    ).convert("RGB")

    img = img.resize((224, 224))

    img_array = np.array(
        img
    ).astype("float32") / 255.0

    input_tensor = tf.convert_to_tensor(
        img_array[None, ...],
        dtype=tf.float32
    )

    # -----------------------------
    # Create gradient model
    # -----------------------------

    grad_model = tf.keras.Model(
        inputs=base_model.input,
        outputs=[
            gradcam_layer.output,
            base_model.output
        ]
    )

    # -----------------------------
    # Get convolution output
    # -----------------------------

    with tf.GradientTape() as tape:

        conv_output, base_output = grad_model(
            input_tensor,
            training=False
        )

        # Pass through the classifier
        x = model.layers[2](base_output)
        x = model.layers[3](x)
        prediction = model.layers[4](x)

        malignant_probability = prediction[:, 0]

    # -----------------------------
    # Calculate gradients
    # -----------------------------

    gradients = tape.gradient(
        malignant_probability,
        conv_output
    )

    # -----------------------------
    # Global average pooling
    # -----------------------------

    pooled_gradients = tf.reduce_mean(
        gradients,
        axis=(1, 2)
    )

    conv_output = conv_output[0]
    pooled_gradients = pooled_gradients[0]

    heatmap = tf.reduce_sum(
        conv_output * pooled_gradients,
        axis=-1
    )

    # -----------------------------
    # Normalize
    # -----------------------------

    heatmap = tf.maximum(
        heatmap,
        0
    )

    heatmap = heatmap / (
        tf.reduce_max(heatmap) + 1e-8
    )

    heatmap = heatmap.numpy()

    probability = float(
        malignant_probability.numpy()[0]
    )

    if probability >= 0.5:

        prediction = "MALIGNANT"
        confidence = probability

    else:

        prediction = "BENIGN"
        confidence = 1 - probability

    # -----------------------------
    # DISPLAY
    # -----------------------------

    plt.figure(figsize=(12, 5))

    # Original
    plt.subplot(1, 2, 1)

    plt.imshow(img)

    plt.title(
        f"Original Mammogram\n"
        f"Prediction: {prediction}"
    )

    plt.axis("off")

    # Grad-CAM
    plt.subplot(1, 2, 2)

    plt.imshow(img)

    plt.imshow(
        heatmap,
        cmap="jet",
        alpha=0.5
    )

    plt.title(
        f"Grad-CAM Analysis\n"
        f"Malignant Probability: "
        f"{probability:.2%}"
    )

    plt.axis("off")

    plt.tight_layout()

    plt.show()

    return {
        "prediction": prediction,
        "confidence": confidence,
        "malignant_probability": probability,
        "heatmap": heatmap
    }

test_image = test_df.iloc[0]["image_path"]

print("Image:")
print(test_image)

result = generate_gradcam(test_image)

print("\n===== DIAGNYX AI =====")
print("Prediction:", result["prediction"])
print(
    "Confidence:",
    f"{result['confidence']:.2%}"
)
print(
    "Malignant Probability:",
    f"{result['malignant_probability']:.2%}"
)

import cv2

def generate_gradcam(image_path):

    # Load original image
    original = Image.open(image_path).convert("RGB")
    original = original.resize((224, 224))

    img_array = np.array(original).astype("float32") / 255.0
    input_tensor = tf.convert_to_tensor(
        img_array[None, ...],
        dtype=tf.float32
    )

    # Grad-CAM model
    grad_model = tf.keras.Model(
        inputs=base_model.input,
        outputs=[
            gradcam_layer.output,
            base_model.output
        ]
    )

    # Gradients
    with tf.GradientTape() as tape:

        conv_output, base_output = grad_model(
            input_tensor,
            training=False
        )

        x = model.layers[2](base_output)
        x = model.layers[3](x)
        prediction = model.layers[4](x)

        probability = prediction[:, 0]

    gradients = tape.gradient(
        probability,
        conv_output
    )

    # Importance weights
    pooled_gradients = tf.reduce_mean(
        gradients,
        axis=(1, 2)
    )

    conv_output = conv_output[0]
    pooled_gradients = pooled_gradients[0]

    heatmap = tf.reduce_sum(
        conv_output * pooled_gradients,
        axis=-1
    )

    # ReLU
    heatmap = tf.maximum(heatmap, 0)

    # Normalize
    heatmap = heatmap / (
        tf.reduce_max(heatmap) + 1e-8
    )

    heatmap = heatmap.numpy()

    # =====================================================
    # IMPORTANT: SMOOTH + UPSCALE HEATMAP
    # =====================================================

    heatmap = cv2.resize(
        heatmap,
        (224, 224),
        interpolation=cv2.INTER_CUBIC
    )

    # Smooth the heatmap
    heatmap = cv2.GaussianBlur(
        heatmap,
        (0, 0),
        sigmaX=7
    )

    # Normalize again
    heatmap = cv2.normalize(
        heatmap,
        None,
        0,
        255,
        cv2.NORM_MINMAX
    ).astype(np.uint8)

    # Create color heatmap
    heatmap_color = cv2.applyColorMap(
        heatmap,
        cv2.COLORMAP_JET
    )

    heatmap_color = cv2.cvtColor(
        heatmap_color,
        cv2.COLOR_BGR2RGB
    )

    # Original image
    original_np = np.array(original)

    # Blend
    overlay = cv2.addWeighted(
        original_np,
        0.60,
        heatmap_color,
        0.40,
        0
    )

    # Prediction
    probability_value = float(
        probability.numpy()[0]
    )

    if probability_value >= 0.5:
        prediction_text = "MALIGNANT"
        confidence = probability_value
    else:
        prediction_text = "BENIGN"
        confidence = 1 - probability_value

    # =====================================================
    # DISPLAY
    # =====================================================

    plt.figure(figsize=(15, 5))

    plt.subplot(1, 3, 1)

    plt.imshow(original_np)

    plt.title(
        "Input Mammogram",
        fontsize=14
    )

    plt.axis("off")

    plt.subplot(1, 3, 2)

    plt.imshow(heatmap_color)

    plt.title(
        "AI Attention Map",
        fontsize=14
    )

    plt.axis("off")

    plt.subplot(1, 3, 3)

    plt.imshow(overlay)

    plt.title(
        f"Grad-CAM Explanation\n"
        f"{prediction_text} | "
        f"{probability_value:.1%}",
        fontsize=14
    )

    plt.axis("off")

    plt.tight_layout()

    plt.show()

    return {
        "prediction": prediction_text,
        "confidence": confidence,
        "malignant_probability": probability_value,
        "heatmap": heatmap,
        "overlay": overlay
    }

result = generate_gradcam(test_df.iloc[0]["image_path"])

!pip -q install gradio

import gradio as gr
import numpy as np
import tensorflow as tf
import cv2
from PIL import Image
import matplotlib.pyplot as plt


# ============================================================
# DIAGNYX AI — PREDICTION + GRAD-CAM
# ============================================================

def predict_mammogram(image):

    if image is None:
        return None, "Please upload a mammogram image.", "", ""

    # --------------------------------------------------------
    # Prepare image
    # --------------------------------------------------------

    original = Image.fromarray(image).convert("RGB")
    original = original.resize((224, 224))

    img_array = np.array(
        original
    ).astype("float32") / 255.0

    input_tensor = tf.convert_to_tensor(
        img_array[None, ...],
        dtype=tf.float32
    )

    # --------------------------------------------------------
    # Grad-CAM
    # --------------------------------------------------------

    grad_model = tf.keras.Model(
        inputs=base_model.input,
        outputs=[
            gradcam_layer.output,
            base_model.output
        ]
    )

    with tf.GradientTape() as tape:

        conv_output, base_output = grad_model(
            input_tensor,
            training=False
        )

        x = model.layers[2](base_output)
        x = model.layers[3](x)
        prediction = model.layers[4](x)

        malignant_probability = prediction[:, 0]

    gradients = tape.gradient(
        malignant_probability,
        conv_output
    )

    pooled_gradients = tf.reduce_mean(
        gradients,
        axis=(1, 2)
    )

    conv_output = conv_output[0]
    pooled_gradients = pooled_gradients[0]

    heatmap = tf.reduce_sum(
        conv_output * pooled_gradients,
        axis=-1
    )

    heatmap = tf.maximum(
        heatmap,
        0
    )

    heatmap = heatmap / (
        tf.reduce_max(heatmap) + 1e-8
    )

    heatmap = heatmap.numpy()

    # --------------------------------------------------------
    # Smooth heatmap
    # --------------------------------------------------------

    heatmap = cv2.resize(
        heatmap,
        (224, 224),
        interpolation=cv2.INTER_CUBIC
    )

    heatmap = cv2.GaussianBlur(
        heatmap,
        (0, 0),
        7
    )

    heatmap = cv2.normalize(
        heatmap,
        None,
        0,
        255,
        cv2.NORM_MINMAX
    ).astype(np.uint8)

    heatmap_color = cv2.applyColorMap(
        heatmap,
        cv2.COLORMAP_JET
    )

    heatmap_color = cv2.cvtColor(
        heatmap_color,
        cv2.COLOR_BGR2RGB
    )

    # --------------------------------------------------------
    # Overlay
    # --------------------------------------------------------

    original_np = np.array(original)

    overlay = cv2.addWeighted(
        original_np,
        0.60,
        heatmap_color,
        0.40,
        0
    )

    # --------------------------------------------------------
    # Prediction
    # --------------------------------------------------------

    probability = float(
        malignant_probability.numpy()[0]
    )

    if probability >= 0.5:

        prediction_text = "MALIGNANT"
        confidence = probability

    else:

        prediction_text = "BENIGN"
        confidence = 1 - probability

    # --------------------------------------------------------
    # UI outputs
    # --------------------------------------------------------

    prediction_display = (
        f"### AI Prediction\n"
        f"## {prediction_text}"
    )

    confidence_display = (
        f"### Confidence\n"
        f"## {confidence:.1%}"
    )

    probability_display = (
        f"### Malignant Probability\n"
        f"## {probability:.1%}"
    )

    return (
        overlay,
        prediction_display,
        confidence_display,
        probability_display
    )


# ============================================================
# UI
# ============================================================

with gr.Blocks(
    title="Diagnyx AI"
) as demo:

    gr.Markdown(
        """
        # 🩺 DIAGNYX AI
        ### Explainable AI for Breast Cancer Screening

        **Upload a mammogram to receive an AI-assisted
        prediction and Grad-CAM visual explanation.**
        """
    )

    with gr.Row():

        with gr.Column():

            image_input = gr.Image(
                type="numpy",
                label="Upload Mammogram"
            )

            analyze_button = gr.Button(
                "🔍 Analyze Mammogram",
                variant="primary"
            )

        with gr.Column():

            heatmap_output = gr.Image(
                label="Grad-CAM Explanation"
            )

    gr.Markdown(
        "## AI Analysis"
    )

    with gr.Row():

        prediction_output = gr.Markdown(
            "### AI Prediction\nWaiting..."
        )

        confidence_output = gr.Markdown(
            "### Confidence\nWaiting..."
        )

        probability_output = gr.Markdown(
            "### Malignant Probability\nWaiting..."
        )

    gr.Markdown(
        """
        ---
        **⚠️ Clinical Decision Support:**
        This prototype is intended to assist healthcare
        professionals. AI output should not replace
        professional clinical judgment.

        **Grad-CAM:** The highlighted region represents
        areas that contributed to the model's prediction;
        it is not a tumor segmentation mask.
        """
    )

    analyze_button.click(
        fn=predict_mammogram,
        inputs=image_input,
        outputs=[
            heatmap_output,
            prediction_output,
            confidence_output,
            probability_output
        ]
    )


demo.launch(share=True)
